---
title: 'Descriptive Analysis of Community Change'
output:
  html_document:
    theme: readable
    df_print: paged
    highlight: tango
    toc: yes
    toc_float: no
    css: 'lab-instructions.css'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo=TRUE, message=F, warning=F, eval=T, fig.width=10 )
```





```{r}
library( dplyr )
library( knitr )
library( pander )
library( stargazer )
library( scales )

library( DescTools )

library( nFactors )
library( corpcor )
library( GPArotation )
library( psych )
library( corrplot )



# set stargazer type to text for 
# previewing in RMD docs but
# convert to type HTML when knitting
# (next code chunk)

s.type <- "text"  
```



```{r, echo=T}
###################################
#
#     STARGAZER SETTINGS
#
###################################

# DO NOT RUN CHUNK UNLESS KNITTING:
# changes table formats to html
# before rendering RMD docs

s.type <- "html"
```



Helper functions for the **pairs()** correlation table: 

```{r}
panel.cor <- function(x, y, digits=2, prefix="", cex.cor)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y))
    txt <- format(c(r, 0.123456789), digits=digits)[1]
    txt <- paste(prefix, txt, sep="")
    if(missing(cex.cor)) cex <- 0.8/strwidth(txt)
    
    test <- cor.test(x,y)
    # borrowed from printCoefmat
    Signif <- symnum(test$p.value, corr = FALSE, na = FALSE,
                  cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1),
                  symbols = c("***", "**", "*", ".", " "))
    
    text(0.5, 0.5, txt, cex = 1.5 )
    text(.7, .8, Signif, cex=cex, col=2)
}

panel.smooth <- function (x, y, col = par("col"), bg = NA, pch = par("pch"), 
	cex = 0.5, col.smooth = "red", span = 2/3, iter = 3, ...) 
{
	points(x, y, pch = 19, col = gray(0.7,0.2), bg = bg, cex = cex)
	ok <- is.finite(x) & is.finite(y)
	if (any(ok)) 
		lines(stats::lowess(x[ok], y[ok], f = span, iter = iter), 
			col = col.smooth, lwd=2, ...)
}

# custom plot
jplot <- function( x1, x2, lab1="", lab2="", draw.line=T, ... )
{

	plot( x1, x2,
	      pch=19, 
	      col=gray(0.6, alpha = 0.2), 
	      cex=0.5,  
	      bty = "n",
	      xlab=lab1, 
	      ylab=lab2, cex.lab=1.5,
        ... )

	if( draw.line==T ){ 
		ok <- is.finite(x1) & is.finite(x2)
		lines( lowess(x2[ok]~x1[ok]), col="red", lwd=3 ) }

}
```






## Load Data


```{r}
URL <- "https://github.com/DS4PS/cpp-529-master/raw/master/data/ltdb_std_2010_sample.rds"
census.dat <- readRDS(gzcon(url( URL )))


head( census.dat )

keep.these <- c("pnhwht12", "pnhblk12", "phisp12", "pntv12", "pfb12", "polang12", 
"phs12", "pcol12", "punemp12", "pflabf12", "pprof12", "pmanuf12", 
"pvet12", "psemp12", "hinc12", "incpc12", "ppov12", "pown12", 
"pvac12", "pmulti12", "mrent12", "mhmval12", "p30old12", "p10yrs12", 
"p18und12", "p60up12", "p75up12", "pmar12", "pwds12", "pfhh12")

d <- census.dat[ keep.these ]

d2 <- apply( d, 2, scale )

head( d2[,1:6] ) 

d3 <- as.data.frame( d2 )

plot( d3$pnhwht12, pch=19 )

```




## Index Construction 

```{r}

# TRUNCATE OUTLIERS AT 2 SDevs

# library( DescTools )
# Winsorize(x, minval = NULL, maxval = NULL, probs = c(0.05, 0.95),
#           na.rm = FALSE, type = 7)


d4 <- lapply( d3, Winsorize )
d5 <- as.data.frame( d4 )


d3 <- as.data.frame(d3)
dim1 <- d3$pown12 + d3$pmulti12 + d3$p10yrs12 + d3$pwds12 + d3$pfhh12   
dim2 <- d3$pnhwht12 + d3$pnhblk12 + d3$phisp12 + d3$pfb12 + d3$polang12
dim3 <- d3$pcol12 + d3$phs12 + d3$pprof12 + d3$hinc12 + d3$mhmval12

```


### Index 1 - Community Stability 

```{r}
ds1 <- d5[ c("pown12", "pmulti12", "p10yrs12", "pwds12", "pfhh12") ]


corrplot( cor(ds1, use="complete.obs"), 
   order = "hclust", tl.col='black', tl.cex=.75 ) 

ds1$pown12 <- - ds1$pown12

corrplot( cor(ds1, use="complete.obs"), 
   order = "hclust", tl.col='black', tl.cex=.75 ) 


alpha( ds1 )

ds1.sub <- ds1[ c("pown12", "pmulti12", "p10yrs12", "pfhh12") ]

corrplot( cor(ds1.sub, use="complete.obs"), 
   order = "hclust", tl.col='black', tl.cex=.75 ) 


alpha( ds1.sub )

```


### Index 2 - Diversity 

```{r}

ds2 <- d5[ c("pnhwht12", "pnhblk12", "phisp12", "pfb12", "polang12") ]

# Check direction

corrplot( cor(ds2, use="complete.obs"), 
   order = "hclust", tl.col='black', tl.cex=.75 ) 

# flip percent white 

ds2$pnhwht12 <- - ds2$pnhwht12

corrplot( cor(ds2, use="complete.obs"), 
   order = "hclust", tl.col='black', tl.cex=.75 ) 

# check cronbach's alpha for scale fit

alpha( ds2 )

# drop percent black to see if it improves 

ds2.sub <- select( ds2, - pnhblk12 )

alpha( ds2.sub )

```


### Index 3 - Human Capital 

```{r}
ds3 <- d5[ c("pcol12", "phs12", "pprof12", "hinc12", "mhmval12") ]

corrplot( cor(ds3, use="complete.obs"), 
   order = "hclust", tl.col='black', tl.cex=.75 ) 

ds3$phs12 <- - ds3$phs12

corrplot( cor(ds3, use="complete.obs"), 
   order = "hclust", tl.col='black', tl.cex=.75 ) 

alpha( ds3 )

```







## Factor Analysis

https://gaopinghuang0.github.io/2018/02/09/exploratory-factor-analysis-notes-and-R-code#factor-extraction-here-pca

https://quantdev.ssri.psu.edu/tutorials/intro-basic-exploratory-factor-analysis



```{r}
ds.full <- cbind( ds1, ds2, ds3 )

corrplot( cor(ds.full, use="complete.obs"), 
   order = "hclust", tl.col='black', tl.cex=.75 ) 


dsf2 <- ds.full[ 
c("pown12", "pmulti12", "p10yrs12", "pfhh12", "pnhwht12", 
"phisp12", "pfb12", "polang12", "pcol12", "phs12", 
"pprof12", "hinc12", "mhmval12") ]

corrplot( cor(dsf2, use="complete.obs"), 
   order = "original", tl.col='black', tl.cex=.75 ) 



these <- c("pown12", "pmulti12", "p10yrs12", "pwds12", "pfhh12",  
"pnhwht12", "pnhblk12", "phisp12", "pfb12", "polang12",
"pcol12", "phs12", "pprof12", "hinc12", "mhmval12" )

d10 <- d5[ these ]

corrplot(cor(d10, use="complete.obs"), order = "hclust", tl.col='black', tl.cex=.75) 
```


```{r}

d5 <- ds.full
mydata <- d5

# library( nFactors )
# library( corpcor )
# library( GPArotation )
# library( psych )
# library( corrplot )


ev <- eigen(cor(mydata)) # get eigenvalues
ap <- parallel(subject=nrow(mydata),var=ncol(mydata),
  rep=100,cent=.05)
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)



corrplot(cor(d5, use="complete.obs"), order = "hclust", tl.col='black', tl.cex=.75) 




pc5 <- principal( d5, nfactors = 5, rotate = "varimax", scores = TRUE )

pc5 <- fa( d5, nfactors = 5, rotate = "varimax", scores = TRUE )


d6 <- predict( pc5, d5 ) %>% as.data.frame()


fa5 <- factanal( d5, factors=5, rotation = "varimax", scores = "regression" )

print.psych( pc5, cut = 0.3, sort = TRUE )


fit <- factor.pa(mydata, nfactors=6, rotate="varimax")
fit # print results


# plot factor 1 by factor 2
load <- fit$loadings[,1:2]
plot(load,type="n") # set up plot
text(load,labels=names(mydata),cex=.7) # add variable names
```


<br>
<br>

<hr>

<br>
<br>






<style>
blockquote {
    padding: 11px 22px;
    margin: 0 0 22px;
    font-size: 18px;
    border-left: 5px solid lightgray;
}

</style>

